apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yl-4-qjv4-python
  janus-idp.io/tekton: yl-4-qjv4-python
  backstage.io/kubernetes-id: yl-4-qjv4-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yl-4-qjv4-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
